theme: jekyll-theme-primer

title: Drone_SOP

description: Drone SOP reference site

exclude:
  - Python_Code/
  - "Markdown Docs/"
  - TODO/
  - "_tmp safety copies/"
  - "test file archived/"
  - "**/__pycache__/"
