#!/usr/bin/env python3
"""Build Batch 6 candidate pool for Advanced RPAS quiz expansion."""
import json
from pathlib import Path

TODAY = "2026-10-01"

CATEGORY_TARGETS = {
    "theory-of-flight": 5,
    "visual-observers": 4,
    "notams": 4,
    "abnormal": 4,
    "human-factors": 4,
    "maintenance": 4,
    "aircraft-systems": 4,
    "safety": 4,
    "aerodromes": 3,
    "flight-planning": 3,
    "radio": 3,
    "airspace": 3,
    "navigation": 3,
    "weather": 1,
    "regulations": 1,
}

KNOWLEDGE = {
    "regulations": ("1", "Air law, air traffic rules and procedures"),
    "airspace": ("1", "Air law, air traffic rules and procedures"),
    "aerodromes": ("6", "Flight operations"),
    "notams": ("6", "Flight operations"),
    "weather": ("4", "Meteorology"),
    "visual-observers": ("6", "Flight operations"),
    "human-factors": ("3", "Human factors"),
    "aircraft-systems": ("2", "RPA airframes, power plants, propulsion and systems"),
    "maintenance": ("2", "RPA airframes, power plants, propulsion and systems"),
    "abnormal": ("6", "Flight operations"),
    "flight-planning": ("6", "Flight operations"),
    "radio": ("8", "Radiotelephony"),
    "navigation": ("5", "Navigation"),
    "safety": ("6", "Flight operations"),
    "theory-of-flight": ("7", "Theory of flight"),
}


def rotated_choices(correct, distractors, seed):
    choices = [correct, *distractors]
    shift = seed % 4
    rotated = choices[shift:] + choices[:shift]
    return rotated, rotated.index(correct)


def question(
    qid,
    category,
    difficulty,
    stem,
    correct,
    distractors,
    rationale,
    topic,
    objective,
    source,
    source_refs,
    exact_refs,
    exam_scope="core-advanced",
    exam_level="advanced",
):
    choices, answer_index = rotated_choices(correct, distractors, int(qid.rsplit("-", 1)[1]))
    section, area = KNOWLEDGE[category]
    return {
        "id": qid,
        "category": category,
        "difficulty": difficulty,
        "question": stem,
        "choices": choices,
        "answerIndex": answer_index,
        "rationale": rationale,
        "source": source,
        "sourceRefs": source_refs,
        "exactRefs": exact_refs,
        "lastVerified": TODAY,
        "examScope": exam_scope,
        "examLevel": exam_level,
        "tp15263Section": section,
        "knowledgeArea": area,
        "knowledgeTopic": topic,
        "learningObjective": objective,
        "origin": {
            "type": "batch6-generated",
            "batch": "Batch 6",
            "request": "Generate 50 Additional Questions for our Adv Drone Quiz",
        },
    }


TP = "ref-tp-15263"
CARS = "ref-justice-cars"
AIM = "ref-tc-aim-full"
RPA = "ref-tc-aim-rpa-2026-1"
DAH = "ref-navcanada-dah"
VFR = "ref-navcanada-vfr-phraseology"
ROC = "ref-roc-a-study-guide"


def tp_ref(section, title, topic, objective):
    return {"source": "TP 15263", "section": str(section), "sectionTitle": title, "topic": topic, "objective": objective}


def cars_ref(section, title, topic):
    return {"source": "CARs", "section": section, "title": title, "topic": topic}


SPECS = [
    question(
        "b6-theory-001",
        "theory-of-flight",
        "hard",
        "A multirotor is hovering in gusty wind near the edge of its published wind limit. Which control concern best explains why the pilot should keep a larger safety margin?",
        "The flight controller may need increasingly large control and power corrections, leaving less authority for a sudden gust or manoeuvre.",
        ["A multirotor always becomes more stable as wind increases.", "Only fixed-wing aircraft are affected by gust loading.", "Wind affects video quality but not controllability."],
        "TP 15263 theory-of-flight knowledge includes stability, control, and performance limits. Near a published limit, extra control margin matters because disturbances can consume remaining authority quickly.",
        "Control margin near aircraft limits",
        "Apply stability and control concepts to decide whether wind conditions leave enough margin for safe RPAS control.",
        "TP 15263 Section 7",
        [TP],
        [tp_ref(7, "Theory of flight", "Stability and control", "Explain aircraft stability, control, and performance effects relevant to RPAS operation.")],
    ),
    question(
        "b6-theory-002",
        "theory-of-flight",
        "medium",
        "A fixed-wing RPA launches with a heavier mapping payload than usual but the same wing and battery. What performance change should the pilot expect?",
        "Higher stall speed and reduced climb/endurance margin compared with the lighter configuration.",
        ["Lower stall speed because weight increases inertia.", "No change unless the centre of gravity moves outside limits.", "Only radio range changes."],
        "Increased weight raises the lift required for flight and generally increases stall speed while reducing climb and endurance margins.",
        "Weight effect on performance",
        "Explain how increased operating weight affects stall speed, climb performance, and endurance.",
        "TP 15263 Sections 2 and 7",
        [TP],
        [tp_ref(7, "Theory of flight", "Weight, lift and stall speed", "Describe how weight affects lift requirement and aircraft performance.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-theory-003",
        "theory-of-flight",
        "hard",
        "A quadcopter is descending vertically into its own disturbed downwash and becomes mushy despite adequate battery power. What aerodynamic issue is most relevant?",
        "The aircraft may be operating in recirculating/settling airflow where added power does not immediately restore normal lift.",
        ["The compass has reversed magnetic north.", "A higher descent rate always improves rotor efficiency.", "The camera gimbal is absorbing lift."],
        "Rotorcraft can lose lift effectiveness in disturbed descending airflow. The operational response is to recover with margin rather than relying only on added throttle.",
        "Rotor downwash and descent performance",
        "Recognize rotorcraft performance hazards during vertical descent and choose conservative recovery actions.",
        "TP 15263 Section 7",
        [TP],
        [tp_ref(7, "Theory of flight", "Rotorcraft lift and airflow", "Identify rotorcraft aerodynamic conditions that affect control and lift.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-theory-004",
        "theory-of-flight",
        "medium",
        "A fixed-wing RPA is trimmed for normal cruise, but the pilot commands a steep bank to turn inside a small survey area. What must the pilot remember about stall margin?",
        "Banking increases load factor, so stall margin can decrease even if airspeed appears acceptable for level flight.",
        ["A banked turn lowers the load factor below one.", "Stall margin is independent of manoeuvring.", "Only multirotors can stall in turns."],
        "In a banked turn, the aircraft must produce more lift than in straight-and-level flight. That raises effective stall speed and reduces margin.",
        "Load factor in turns",
        "Apply load-factor concepts to fixed-wing RPA turn planning and stall avoidance.",
        "TP 15263 Section 7",
        [TP],
        [tp_ref(7, "Theory of flight", "Load factor and stall margin", "Explain how manoeuvring affects stall speed and control margin.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-theory-005",
        "theory-of-flight",
        "medium",
        "A pilot notices the RPA requires noticeably more power to hold altitude on a hot afternoon at a high-elevation site. Which explanation best connects theory of flight to the go/no-go decision?",
        "Lower air density reduces aerodynamic and propulsion performance, so takeoff, climb, and endurance margins may be reduced.",
        ["Warm air always improves propeller thrust.", "Density altitude affects only crewed aircraft altimeters.", "The only concern is battery display brightness."],
        "Meteorology and theory of flight intersect in density-altitude effects. Lower density can reduce lift, propeller thrust, cooling, and endurance margin.",
        "Density altitude and RPAS performance",
        "Relate air density to RPA lift, propulsion, cooling, climb, and endurance performance.",
        "TP 15263 Sections 4 and 7",
        [TP, AIM],
        [tp_ref(4, "Meteorology", "Density altitude and aircraft performance", "Assess density-altitude effects on anticipated launch and flight performance."), tp_ref(7, "Theory of flight", "Lift and propulsion performance", "Explain performance effects caused by air density changes.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-vo-001",
        "visual-observers",
        "hard",
        "During an EVLOS operation, one observer can see the RPA clearly but cannot see the approach path of nearby crewed traffic because of a ridge. What is the key issue?",
        "The observer must be able to maintain unaided visual awareness of the relevant operating airspace, not merely see the RPA.",
        ["Seeing the RPA alone is enough for all observer duties.", "The observer can rely entirely on the pilot's screen.", "Terrain shielding improves observer effectiveness."],
        "EVLOS depends on observers supporting traffic and hazard detection. A blocked view of relevant airspace can defeat the purpose of the observer position.",
        "EVLOS observer field of view",
        "Assess whether a visual observer position supports unaided monitoring of the operating airspace.",
        "CAR 901.74; TP 15263 Section 6",
        [CARS, TP],
        [cars_ref("901.74", "Extended VLOS Operations and Sheltered Operations", "Unaided visual contact with the RPA and operating airspace."), tp_ref(6, "Flight operations", "Visual observer duties", "Determine suitable visual-observer placement and responsibilities.")],
    ),
    question(
        "b6-vo-002",
        "visual-observers",
        "medium",
        "A visual observer reports 'traffic left' but does not identify altitude, direction, or relative movement. What is the best crew coordination improvement?",
        "Use brief, standardized traffic calls that include relative bearing/location, direction, altitude estimate when possible, and urgency.",
        ["Require the observer to stop scanning and write a full report first.", "Avoid traffic calls unless a collision is certain.", "Have the observer speak only after landing."],
        "Visual observers support timely collision-avoidance decisions. Standard, concise calls reduce ambiguity and workload.",
        "Visual observer traffic calls",
        "Use concise crew communication to transfer traffic information quickly and accurately.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Crew communication and workload", "Apply effective communication practices in crewed operations."), tp_ref(6, "Flight operations", "Visual observer duties", "Coordinate visual-observer traffic detection with pilot action.")],
    ),
    question(
        "b6-vo-003",
        "visual-observers",
        "hard",
        "Two observers cover adjacent segments of an EVLOS route, but neither can see a short transition area between them. What should the pilot conclude before launch?",
        "The route has a coverage gap that must be corrected or the operation changed before relying on those observers.",
        ["The gap is acceptable if both observers can see the control station.", "Only the launch and landing areas need observer coverage.", "Coverage gaps are solved by increasing camera zoom."],
        "Observer coverage must support continuous situational awareness for the operating area being used. A known gap is an operational planning defect.",
        "Observer coverage continuity",
        "Identify and correct visual-observer coverage gaps before an EVLOS operation.",
        "CAR 901.74; TP 15263 Section 6",
        [CARS, TP],
        [cars_ref("901.74", "Extended VLOS Operations and Sheltered Operations", "Conditions for EVLOS operations."), tp_ref(6, "Flight operations", "Crew roles and observer placement", "Plan visual-observer coverage for the operating area.")],
    ),
    question(
        "b6-vo-004",
        "visual-observers",
        "medium",
        "A pilot assigns an observer but never briefs the lost-link route, termination area, or abort words. What is the operational weakness?",
        "The observer cannot reliably support timely emergency or contingency decisions without knowing the planned responses and callouts.",
        ["Observers need only know the aircraft colour.", "Emergency plans are relevant only after the flight.", "Lost-link procedures should be kept from observers to reduce distraction."],
        "Crew members need shared mental models for normal and abnormal procedures. Briefing observers improves response time when conditions change.",
        "Observer briefing for contingencies",
        "Brief visual observers on procedures, hazards, communications, and contingency actions before flight.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Crew coordination", "Explain how briefing supports shared situational awareness."), tp_ref(6, "Flight operations", "Emergency procedures", "Coordinate crew actions for contingencies and emergencies.")],
    ),
    question(
        "b6-notam-001",
        "notams",
        "hard",
        "A NOTAM radius is centred on coordinates near the mission site. The planned route is just outside the published radius, but the contingency landing area is inside it. What is the best interpretation?",
        "The NOTAM is still operationally relevant because contingency volumes and emergency options can be affected, not just the nominal route.",
        ["Ignore it because the planned route is outside the circle.", "Use the NOTAM only if the centre point is inside the launch area.", "Treat all circular NOTAMs as advisory only."],
        "Pre-flight aeronautical information review should account for the whole operational volume, including contingency areas, not just the ideal track.",
        "NOTAM radius and operational volume",
        "Interpret NOTAM geography against planned, contingency, and emergency operating areas.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Pre-flight information and site survey", "Use current aeronautical information for flight planning."), {"source": "TC AIM", "section": "MAP/GEN/RPA", "topic": "NOTAM and aeronautical information use"}],
    ),
    question(
        "b6-notam-002",
        "notams",
        "hard",
        "A NOTAM lists an obstacle from the surface to 450 ft AGL, while the RPA mission is planned at 380 ft AGL nearby. What should the pilot do with that information?",
        "Assess the obstacle location, height reference, lateral clearance, and route/contingency margins before deciding whether the mission remains safe.",
        ["Ignore it because the RPA is below 400 ft AGL.", "Assume the obstacle top is exactly at the launch elevation.", "Proceed if the obstacle is not visible from launch."],
        "Obstacle NOTAMs can affect route selection and contingency planning. The pilot must reconcile height references and margins, not rely on the generic 400 ft limit.",
        "Obstacle NOTAM interpretation",
        "Use obstacle NOTAM data to evaluate route, altitude, and contingency margins.",
        "TP 15263 Sections 5 and 6; TC AIM",
        [TP, AIM],
        [tp_ref(5, "Navigation", "Altitude and obstacle interpretation", "Relate altitude references and obstacle data to route planning."), tp_ref(6, "Flight operations", "Site survey hazards", "Identify hazards affecting planned and contingency flight areas.")],
    ),
    question(
        "b6-notam-003",
        "notams",
        "medium",
        "A NOTAM becomes active halfway through a planned one-hour flight. What is the best planning response?",
        "Plan the operation so it is complete before activation or adjust the route/time; do not assume the start time controls the entire flight.",
        ["Launch before activation and continue normally.", "Use only the NOTAM issue time, not the active time.", "Ignore activation times for short RPAS flights."],
        "NOTAM active periods must be compared with the entire mission window, including delays and recovery time.",
        "NOTAM timing",
        "Compare NOTAM active times with the full RPAS operation window and adjust plans accordingly.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Pre-flight planning and aeronautical information", "Apply time-valid aeronautical information to the planned operation."), {"source": "TC AIM", "topic": "NOTAM validity and active periods"}],
    ),
    question(
        "b6-notam-004",
        "notams",
        "hard",
        "A NOTAM describes blasting activity near the operating area with a short daily time window. Why should the pilot avoid treating it as irrelevant just because the aircraft will remain low?",
        "The activity may create airspace, ground-risk, distraction, emergency-response, or exclusion-zone hazards that affect the site survey and timing.",
        ["Low-altitude RPAS operations are never affected by ground activity.", "Blasting NOTAMs apply only above 400 ft.", "Only crewed aircraft need to read activity NOTAMs."],
        "NOTAMs may identify hazards that matter to launch/recovery, bystanders, emergency access, or operating-area suitability even when altitude seems low.",
        "Activity NOTAM operational relevance",
        "Evaluate activity NOTAMs as part of the site survey and go/no-go decision.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Site survey and operational risk", "Identify temporary hazards and restrictions before flight."), {"source": "TC AIM", "topic": "NOTAM activity information"}],
    ),
    question(
        "b6-abn-001",
        "abnormal",
        "hard",
        "The RPA loses command link and its programmed return path would cross the edge of controlled airspace. What is the pilot's best immediate priority?",
        "Follow the lost-link procedure and notify the appropriate ATS unit if the uncontrolled RPA has entered or is likely to enter controlled airspace.",
        ["Wait until the battery is depleted before notifying anyone.", "Assume the return path is authorized because it was programmed.", "Cancel the mission log to avoid confusion."],
        "CARs require prompt notification when an uncontrolled RPA enters or is likely to enter controlled airspace. Lost-link planning should anticipate that obligation.",
        "Lost link near controlled airspace",
        "Apply emergency notification obligations when an uncontrolled RPA threatens controlled airspace.",
        "CAR 901.15; TP 15263 Sections 1 and 6",
        [CARS, TP],
        [cars_ref("901.15", "Inadvertent entry into controlled airspace", "Immediate notification if an uncontrolled RPA enters or is likely to enter controlled airspace."), tp_ref(6, "Flight operations", "Emergency procedures", "Apply lost-link and flyaway procedures.")],
    ),
    question(
        "b6-abn-002",
        "abnormal",
        "medium",
        "A low-battery warning appears earlier than expected because of stronger wind aloft. What is the best decision-making principle?",
        "Treat the warning as a changed condition, abandon non-essential mission objectives, and recover with adequate reserve.",
        ["Continue until the planned photo set is complete.", "Climb higher to improve battery voltage.", "Ignore warnings that occur before the planned return point."],
        "Abnormal procedures require conservative decisions when actual energy use differs from the plan. Mission completion is secondary to safe recovery.",
        "Early low-battery abnormal response",
        "Respond to changing endurance margins by prioritizing safe recovery over mission completion.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Decision-making under pressure", "Recognize plan continuation bias and make conservative decisions."), tp_ref(6, "Flight operations", "Abnormal and emergency procedures", "Apply contingency procedures for degraded aircraft state.")],
    ),
    question(
        "b6-abn-003",
        "abnormal",
        "hard",
        "During an automated mapping run, telemetry shows repeated navigation-quality warnings although the aircraft still appears stable on video. What should the pilot do?",
        "Pause or terminate the automated task and regain a safe mode of operation before navigation quality degrades further.",
        ["Rely on the video image and continue the automated run.", "Disable all warnings for the remainder of the flight.", "Increase distance from the pilot to improve automation."],
        "Navigation-quality warnings are abnormal cues. Continuing automation without reassessment can allow a recoverable condition to become an emergency.",
        "Automation warning response",
        "Use telemetry and warning cues to interrupt automation and preserve safe control.",
        "TP 15263 Sections 2, 3 and 6",
        [TP],
        [tp_ref(2, "RPA systems", "Command, control and navigation system awareness", "Recognize system indications affecting safe operation."), tp_ref(6, "Flight operations", "Abnormal procedures", "Respond to degraded system status during flight.")],
    ),
    question(
        "b6-abn-004",
        "abnormal",
        "medium",
        "A designated emergency landing area is occupied by vehicles when a contingency occurs. What does this reveal about the original plan?",
        "Emergency sites must be checked for current suitability and alternates considered because site conditions can change during the operation.",
        ["A listed emergency site is always available once chosen.", "The pilot must continue to the original site regardless of obstacles.", "Emergency areas are needed only for fixed-wing RPA."],
        "Contingency planning is dynamic. A site that was suitable during planning may become unusable and must be monitored or backed up.",
        "Emergency landing site currency",
        "Maintain current contingency options and adapt when a planned emergency area becomes unsuitable.",
        "TP 15263 Section 6",
        [TP],
        [tp_ref(6, "Flight operations", "Contingency and emergency planning", "Select and maintain suitable contingency and emergency recovery areas.")],
    ),
    question(
        "b6-hf-001",
        "human-factors",
        "hard",
        "A pilot feels pressure to finish a paid inspection before rain arrives and starts discounting warning signs from the aircraft. Which human factor is most relevant?",
        "Plan-continuation bias and external pressure can degrade judgment, so the pilot should deliberately reassess against go/no-go criteria.",
        ["Paid work eliminates the need for conservative judgment.", "Weather pressure improves attention.", "Human factors apply only to crewed aircraft pilots."],
        "External pressure and sunk-cost thinking can push pilots to continue when conditions no longer meet the plan. Structured reassessment counters that bias.",
        "Plan-continuation bias",
        "Recognize pressure-driven decision errors and use structured go/no-go criteria.",
        "TP 15263 Section 3",
        [TP],
        [tp_ref(3, "Human factors", "Decision-making and hazardous attitudes", "Identify human factors that affect pilot judgment and risk management.")],
    ),
    question(
        "b6-hf-002",
        "human-factors",
        "medium",
        "A visual observer has been scanning a bright sky for 25 minutes and begins missing radio calls and traffic cues. What is the best mitigation?",
        "Rotate duties or pause the operation before fatigue and visual scanning performance degrade further.",
        ["Ask the observer to stare continuously at one point.", "Reduce crew communication to zero.", "Assume fatigue cannot affect short RPAS flights."],
        "Human performance degrades with fatigue, visual strain, and workload. Crew rotation and pauses preserve detection and communication effectiveness.",
        "Observer fatigue",
        "Apply fatigue and workload management to RPAS crew roles.",
        "TP 15263 Section 3",
        [TP],
        [tp_ref(3, "Human factors", "Fatigue, workload and attention", "Explain how fatigue and workload affect performance and situational awareness.")],
    ),
    question(
        "b6-hf-003",
        "human-factors",
        "medium",
        "A pilot focuses on framing the perfect photo and stops monitoring battery, wind drift, and nearby traffic. What human-factor problem is this?",
        "Attention tunnelling, where one task captures attention at the expense of overall situational awareness.",
        ["Improved situational awareness through specialization.", "A maintenance defect.", "A radio phraseology issue only."],
        "Attention tunnelling can cause missed cues. RPAS pilots must manage payload tasks while maintaining aircraft and airspace awareness.",
        "Attention tunnelling",
        "Recognize attention tunnelling and preserve broad situational awareness during payload tasks.",
        "TP 15263 Section 3",
        [TP],
        [tp_ref(3, "Human factors", "Attention and situational awareness", "Identify factors that reduce situational awareness and apply mitigations.")],
    ),
    question(
        "b6-hf-004",
        "human-factors",
        "hard",
        "A crew uses non-standard terms for abort, hold, land, and traffic calls. Why is this risky during an abnormal event?",
        "Ambiguous callouts increase response time and can cause the pilot and observer to take conflicting actions.",
        ["Non-standard terms are always clearer because they are informal.", "Callouts matter only for radio transmissions to ATS.", "Abnormal events are too rare to brief."],
        "Clear shared terminology reduces confusion under stress. Human-factors knowledge includes communication discipline and crew coordination.",
        "Crew callout discipline",
        "Use standardized crew callouts to support timely abnormal and emergency response.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Communication and crew coordination", "Describe communication practices that reduce error."), tp_ref(6, "Flight operations", "Emergency procedures", "Coordinate crew actions using briefed procedures.")],
    ),
    question(
        "b6-maint-001",
        "maintenance",
        "hard",
        "After a minor propeller strike, the aircraft powers up normally and the propeller looks acceptable from a distance. What should the pilot do before the next flight?",
        "Remove the aircraft from service until the propeller, motor, mount, and related structure are inspected according to the manufacturer's instructions.",
        ["Fly a short test over people to confirm vibration.", "Ignore the strike if the app shows no error.", "Only wipe the propeller clean."],
        "Serviceability is not proven by a normal power-up. Propeller strikes can damage rotating components and structure in ways that affect safe flight.",
        "Post-strike serviceability",
        "Assess aircraft serviceability after an event that may damage propulsion or structure.",
        "TP 15263 Section 2; CARs Part IX",
        [TP, CARS],
        [tp_ref(2, "RPA systems", "Maintenance and serviceability", "Identify defects and conditions that make an RPA unfit for flight."), cars_ref("901.29", "Pre-flight Information", "Confirm the aircraft is fit for safe operation before flight.")],
    ),
    question(
        "b6-maint-002",
        "maintenance",
        "medium",
        "A battery pack has slight swelling after charging but still reports normal voltage. What is the best maintenance decision?",
        "Do not use it for flight until it is assessed against manufacturer safety criteria; voltage alone does not prove battery serviceability.",
        ["Use it if the voltage is above 95 percent.", "Freeze it briefly to reduce swelling.", "Use it only for flights near people."],
        "Battery condition includes physical state, temperature, history, and manufacturer limits. Swelling is a serviceability concern even with normal voltage.",
        "Battery physical condition",
        "Evaluate battery serviceability using physical condition and manufacturer limits, not voltage alone.",
        "TP 15263 Section 2",
        [TP],
        [tp_ref(2, "RPA systems", "Power systems and batteries", "Identify battery conditions that affect safe operation.")],
    ),
    question(
        "b6-maint-003",
        "maintenance",
        "hard",
        "A declared RPAS receives a third-party antenna modification before an operation that depends on the aircraft declaration. What must be confirmed?",
        "The modified system still meets the applicable technical requirements and any manufacturer or declaration-related modification instructions.",
        ["Any antenna change automatically improves compliance.", "Declarations are never affected by physical modifications.", "Only the pilot certificate matters."],
        "Advanced privileges may depend on the declared aircraft configuration. A modification can affect whether the system remains eligible for the intended operation.",
        "Modification effect on declaration",
        "Confirm whether modifications affect declared RPAS eligibility for the planned operation.",
        "CAR 901.70; TP 15263 Sections 1 and 2",
        [CARS, TP],
        [cars_ref("901.70", "Operation of a modified remotely piloted aircraft system", "Modified RPAS must continue to meet applicable technical requirements."), tp_ref(2, "RPA systems", "System configuration and maintenance", "Assess configuration changes that affect serviceability or compliance.")],
    ),
    question(
        "b6-maint-004",
        "maintenance",
        "medium",
        "A firmware update changes return-to-home behaviour and geofence settings. What should the pilot do before relying on the aircraft for the next operation?",
        "Review release notes/settings and perform appropriate ground or controlled checks so emergency and boundary behaviours are understood.",
        ["Assume all previous settings are unchanged.", "Disable return-to-home because updates are confusing.", "Rely on memory from the previous firmware version."],
        "Software changes can alter aircraft behaviour. A serviceable aircraft includes known, correctly configured systems before flight.",
        "Firmware and configuration control",
        "Verify system configuration and emergency behaviours after firmware or software changes.",
        "TP 15263 Sections 2 and 6",
        [TP],
        [tp_ref(2, "RPA systems", "Control systems and configuration", "Identify system settings that affect operation."), tp_ref(6, "Flight operations", "Emergency procedures", "Confirm programmed emergency behaviours before flight.")],
    ),
    question(
        "b6-sys-001",
        "aircraft-systems",
        "hard",
        "An RPA shows intermittent compass disagreement during the site survey near a steel structure. What is the best system-aware response?",
        "Relocate or reassess before launch because magnetic interference can affect heading, navigation, and automated flight behaviour.",
        ["Calibrate on top of the steel structure to match local conditions.", "Ignore compass warnings if GPS satellites are available.", "Fly only higher to make the compass immune."],
        "Aircraft-system knowledge includes sensor limitations. Magnetic interference can produce unreliable heading information and degrade automated modes.",
        "Compass interference",
        "Recognize sensor interference and adapt launch/site decisions before flight.",
        "TP 15263 Sections 2 and 6",
        [TP],
        [tp_ref(2, "RPA systems", "Sensors and navigation systems", "Identify system limitations and warnings."), tp_ref(6, "Flight operations", "Site survey", "Identify site hazards affecting aircraft systems.")],
    ),
    question(
        "b6-sys-002",
        "aircraft-systems",
        "medium",
        "The control station tablet overheats and dims in direct sun during pre-flight setup. Why is this more than a comfort issue?",
        "The display and processing device is part of command/control awareness; overheating can reduce visibility, responsiveness, or reliability.",
        ["The tablet is not part of the RPAS operation.", "Screen brightness never affects pilot workload.", "Overheating is useful because it warms batteries."],
        "Ground-control equipment supports safe operation. Display readability and device reliability affect command, monitoring, and workload.",
        "Control station reliability",
        "Assess ground-control station limitations as part of RPAS system readiness.",
        "TP 15263 Section 2",
        [TP],
        [tp_ref(2, "RPA systems", "Ground control station and command link", "Describe control station components and limitations that affect safe operation.")],
    ),
    question(
        "b6-sys-003",
        "aircraft-systems",
        "hard",
        "A mission relies on precise hover beside a building, but GNSS quality fluctuates as the aircraft moves close to the wall. What system limitation is most relevant?",
        "Satellite signal masking or reflection can degrade position hold, so the pilot should plan extra clearance and be ready for manual control or recovery.",
        ["Buildings always improve satellite accuracy.", "GNSS quality matters only during takeoff.", "Position hold is independent of sensor quality."],
        "GNSS and sensor limitations affect automated position hold. Structures can mask or reflect signals, increasing drift risk near obstacles.",
        "GNSS degradation near structures",
        "Recognize GNSS limitations around structures and plan control margins accordingly.",
        "TP 15263 Sections 2 and 5",
        [TP],
        [tp_ref(2, "RPA systems", "Navigation and positioning systems", "Identify limitations of navigation sensors."), tp_ref(5, "Navigation", "GNSS use and limitations", "Apply GNSS limitations to flight planning.")],
    ),
    question(
        "b6-sys-004",
        "aircraft-systems",
        "medium",
        "A payload is mounted slightly off-centre on a multirotor. Why should the pilot care even if total weight remains below the limit?",
        "An off-centre payload can shift balance, increase motor workload, and reduce control or endurance margins.",
        ["Only total weight matters; balance cannot affect multirotors.", "Off-centre loads improve redundancy.", "Payload position affects only image composition."],
        "Aircraft-system and theory knowledge include weight distribution, balance, propulsion workload, and performance margins.",
        "Payload balance",
        "Assess how payload installation affects balance, propulsion workload, and controllability.",
        "TP 15263 Sections 2 and 7",
        [TP],
        [tp_ref(2, "RPA systems", "Payload installation and system effects", "Identify configuration factors affecting aircraft serviceability."), tp_ref(7, "Theory of flight", "Centre of gravity and stability", "Explain how balance affects control and performance.")],
    ),
    question(
        "b6-safety-001",
        "safety",
        "hard",
        "A crewed helicopter appears unexpectedly at low altitude near the site. What is the RPAS pilot's immediate safety priority?",
        "Give way, increase separation, and land or manoeuvre as necessary without creating a new ground hazard.",
        ["Continue because the RPA is smaller.", "Climb toward the helicopter so it can see the RPA.", "Wait for ATC to resolve the conflict in uncontrolled airspace."],
        "RPAS pilots must avoid creating collision hazards and give way to other aircraft while still considering ground risk during avoidance.",
        "Right-of-way and collision avoidance",
        "Apply right-of-way and collision-avoidance principles while managing ground risk.",
        "CAR 901.18; TP 15263 Section 6",
        [CARS, TP],
        [cars_ref("901.18", "Right of Way", "Give way to crewed aircraft."), tp_ref(6, "Flight operations", "Collision avoidance", "Maintain separation from other aircraft and hazards.")],
    ),
    question(
        "b6-safety-002",
        "safety",
        "medium",
        "A member of the public walks toward the landing zone during final approach. What should the crew do?",
        "Abort or hold if safe, re-establish site control, and land only when the area is clear or use a safer alternate.",
        ["Continue landing because final approach has priority.", "Ask the bystander to move after touchdown.", "Descend faster to finish before they arrive."],
        "Site control is dynamic. The crew must prevent bystander exposure during landing and use briefed alternatives when the area becomes unsafe.",
        "Landing zone site control",
        "Maintain public safety and site control during launch and recovery.",
        "TP 15263 Section 6; CARs Part IX",
        [TP, CARS],
        [tp_ref(6, "Flight operations", "Site control and bystander safety", "Manage launch and recovery areas to protect people."), cars_ref("901.28", "Minimum Distance", "Operate at required distances from people unless authorized conditions are met.")],
    ),
    question(
        "b6-safety-003",
        "safety",
        "hard",
        "An evasive manoeuvre would avoid airborne traffic but send the RPA toward a crowd. What should guide the pilot's decision?",
        "Choose the safest available action considering both air and ground risk, including landing or moving to a pre-briefed safer area if possible.",
        ["Air risk always overrides ground risk regardless of consequence.", "Ground risk always overrides air risk regardless of collision potential.", "The pilot should freeze controls until the conflict passes."],
        "Collision avoidance decisions must balance risks to aircraft and people on the ground. Pre-briefed contingency options help avoid forced improvisation.",
        "Balancing air and ground risk",
        "Make collision-avoidance decisions that consider both airborne and ground hazards.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Decision-making under stress", "Make timely decisions under competing risks."), tp_ref(6, "Flight operations", "Collision avoidance and emergency procedures", "Manage air and ground risk during conflicts.")],
    ),
    question(
        "b6-safety-004",
        "safety",
        "medium",
        "A pilot plans to fly over a roadway because no pedestrians are present. What additional safety issue should be considered?",
        "The RPA could distract drivers or fail into moving traffic, so roadway exposure must be included in the risk controls.",
        ["Roadways matter only when pedestrians are standing on them.", "Vehicles are not people, so there is no safety concern.", "A roadway automatically counts as a controlled site."],
        "Public safety includes indirect hazards, including distraction, crash consequences, and emergency access around vehicles.",
        "Roadway indirect risk",
        "Include moving vehicles and indirect public hazards in site-risk assessment.",
        "TP 15263 Section 6",
        [TP],
        [tp_ref(6, "Flight operations", "Site survey and public safety", "Identify hazards to people, property, and other users near the operating area.")],
    ),
    question(
        "b6-aero-001",
        "aerodromes",
        "hard",
        "An uncontrolled aerodrome near the site has no traffic when the pilot arrives, but a NOTAM shows parachute activity later in the day. What should the pilot do?",
        "Account for the full mission window and delay/re-route/cancel if the activity could affect the operation or contingency area.",
        ["Use only the traffic observed on arrival.", "Ignore parachute activity below 400 ft.", "Assume uncontrolled aerodromes cannot have time-sensitive hazards."],
        "Aerodrome risk assessment includes current aeronautical information and the whole operating window, not just observed traffic at setup.",
        "Aerodrome activity timing",
        "Incorporate aerodrome activity and timing into site survey decisions.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Aerodrome proximity and site survey", "Assess aerodrome hazards before and during operations."), {"source": "TC AIM", "topic": "Aerodrome operations and activity information"}],
    ),
    question(
        "b6-aero-002",
        "aerodromes",
        "medium",
        "A heliport is several kilometres away, but its published approach path crosses near the planned survey site. Why does that matter?",
        "Aircraft may be low on approach or departure along that path, so lateral distance to the heliport alone may understate the conflict risk.",
        ["Only the heliport centre point matters.", "Helicopters always remain above RPAS altitudes.", "Published approach paths are irrelevant to site surveys."],
        "Aerodrome/heliport assessment should consider traffic flows and approach/departure paths, not just distance to a reference point.",
        "Heliport approach path risk",
        "Evaluate nearby heliport traffic patterns and approach/departure paths during site survey.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Site survey near aerodromes/heliports", "Assess nearby aircraft routes and traffic patterns."), {"source": "TC AIM", "topic": "Heliport and aerodrome traffic considerations"}],
    ),
    question(
        "b6-aero-003",
        "aerodromes",
        "hard",
        "The CFS indicates an MF area near the planned operation, but the pilot has no radio capability. What is the conservative planning response?",
        "Assess whether the operation can be conducted safely without transmitting, use other coordination methods where appropriate, or choose another time/location.",
        ["Transmit anyway without the required operator qualification.", "Ignore the MF because RPAS are small.", "Assume listening is unnecessary if no aircraft are visible."],
        "MF procedures and radio capability affect situational awareness and coordination. Lack of radio capability must be managed conservatively in planning.",
        "MF area without radio capability",
        "Plan safe operations near MF areas when radio capability or qualification is limited.",
        "TP 15263 Sections 6 and 8; TC AIM",
        [TP, AIM, ROC],
        [tp_ref(6, "Flight operations", "Aerodrome and traffic awareness", "Assess communication needs near aerodromes."), tp_ref(8, "Radiotelephony", "Communication requirements", "Understand radio use and operator requirements.")],
    ),
    question(
        "b6-fp-001",
        "flight-planning",
        "hard",
        "A site survey was completed two weeks ago, but construction fencing now changes public access and emergency landing options. What should happen before launch?",
        "Update the site survey and risk controls using current conditions before deciding whether the operation can proceed.",
        ["Use the earlier survey because it was documented.", "Proceed if the aircraft route itself is unchanged.", "Treat fencing as a privacy issue only."],
        "Site surveys must reflect current conditions. Changed access, bystander flow, and emergency options can alter the go/no-go decision.",
        "Site survey currency",
        "Update site surveys when conditions affecting hazards or mitigations change.",
        "TP 15263 Section 6; CARs Part IX",
        [TP, CARS],
        [tp_ref(6, "Flight operations", "Site survey", "Assess current operating-area hazards and mitigations."), cars_ref("901.27", "Site Survey", "Conduct a site survey before operation.")],
    ),
    question(
        "b6-fp-002",
        "flight-planning",
        "medium",
        "A pilot calculates endurance using calm-wind groundspeed, but the forecast shows a headwind on the return leg. What planning error is present?",
        "The endurance plan ignores wind effect on groundspeed and may overestimate the energy available for safe return.",
        ["Headwind affects only fixed-wing aircraft.", "Return-leg wind is irrelevant if launch wind is calm.", "Battery percentage automatically corrects the flight plan."],
        "Flight planning must account for wind effects on groundspeed, time, and energy margins, especially for the recovery leg.",
        "Wind and endurance planning",
        "Include wind effects in endurance, route, and recovery planning.",
        "TP 15263 Sections 4, 5 and 6",
        [TP],
        [tp_ref(4, "Meteorology", "Wind effects", "Assess wind impact on operation."), tp_ref(5, "Navigation", "Groundspeed and track", "Relate wind to groundspeed and navigation planning."), tp_ref(6, "Flight operations", "Flight planning", "Plan endurance and reserves for the full operation.")],
    ),
    question(
        "b6-fp-003",
        "flight-planning",
        "hard",
        "A mission has a narrow landing zone bordered by spectators on one side and trees on the other. What should the flight plan include before launch?",
        "Defined abort criteria, site-control measures, and an alternate recovery option if the primary landing area becomes unsafe.",
        ["Only the camera shot list.", "A plan to descend faster through the narrow area.", "No alternate if the pilot is experienced."],
        "Flight planning should identify hazards, controls, abort points, and contingency recovery options before the operation begins.",
        "Launch/recovery contingency planning",
        "Build abort criteria and alternate recovery options into the pre-flight plan.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Decision-making and risk management", "Use pre-set criteria to support decisions."), tp_ref(6, "Flight operations", "Launch, recovery and contingency planning", "Plan safe recovery and abort options.")],
    ),
    question(
        "b6-radio-001",
        "radio",
        "medium",
        "Before transmitting on an aerodrome frequency, what should an RPAS crew member do first?",
        "Listen long enough to understand current traffic and avoid blocking or stepping on other transmissions.",
        ["Transmit immediately to claim priority.", "Use the frequency for crew chatter first.", "Assume silence means the radio is broken."],
        "Good radio practice starts with listening, then transmitting concise relevant information using standard phraseology.",
        "Listen before transmitting",
        "Use proper radio etiquette to avoid interfering with other communications.",
        "TP 15263 Section 8; NAV CANADA VFR Phraseology",
        [TP, VFR],
        [tp_ref(8, "Radiotelephony", "Radio etiquette", "Give examples of practices that avoid interfering with communications."), {"source": "NAV CANADA", "title": "VFR Phraseology Guide", "topic": "Concise radio communications"}],
    ),
    question(
        "b6-radio-002",
        "radio",
        "hard",
        "A pilot receives an ATC instruction that conflicts with the requested RPAS altitude block. What is the correct operational response?",
        "Comply with the ATC instruction or obtain clarification/amendment before operating outside the cleared conditions.",
        ["Use the originally requested altitude because it was in the application.", "Ignore ATC once airborne below 400 ft.", "Proceed and explain after landing."],
        "Controlled-airspace authorization is conditional, and pilots must comply with ATC instructions or clarify before deviating.",
        "ATC instruction compliance",
        "Apply ATC instruction and readback/clarification principles to RPAS operations.",
        "CAR 901.72; TP 15263 Sections 1 and 8",
        [CARS, TP],
        [cars_ref("901.72", "Compliance with air traffic control instructions", "Comply with ATC instructions."), tp_ref(8, "Radiotelephony", "ATC communications", "Use clear communications with ATS.")],
    ),
    question(
        "b6-radio-003",
        "radio",
        "medium",
        "An RPAS crew plans to monitor a frequency for situational awareness but not transmit. What should still be briefed?",
        "Who monitors, what traffic information matters, and how relevant information will be relayed to the pilot without distracting from aircraft control.",
        ["Nothing, because receiving is passive.", "Only the radio volume setting.", "A plan to transmit without a certificate if busy."],
        "Monitoring can improve awareness only if the crew knows what to listen for and how to communicate it effectively.",
        "Radio monitoring crew briefing",
        "Integrate radio monitoring into crew coordination and workload management.",
        "TP 15263 Sections 3, 6 and 8",
        [TP],
        [tp_ref(3, "Human factors", "Workload and communication", "Manage information flow within the crew."), tp_ref(8, "Radiotelephony", "Common frequencies and monitoring", "Understand operational use of aviation frequencies.")],
    ),
    question(
        "b6-air-001",
        "airspace",
        "hard",
        "A CYA area is published as advisory airspace along the planned route. What should the RPAS pilot do before deciding it is acceptable to enter?",
        "Check the current status, activity type, times, altitudes, and risk to the operation, then apply mitigations or avoid it if necessary.",
        ["Treat all CYA areas as prohibited.", "Ignore advisory airspace because it is never active.", "Enter if below 400 ft without reviewing details."],
        "Class F advisory areas identify activities that can affect safety. The pilot should review DAH/NOTAM details and assess the specific risk.",
        "Class F advisory airspace",
        "Interpret Class F advisory airspace and decide whether mitigations or avoidance are required.",
        "TP 15263 Section 1; DAH; TC AIM",
        [TP, DAH, AIM],
        [tp_ref(1, "Air law, air traffic rules and procedures", "Airspace classification and restrictions", "Interpret airspace that affects RPAS operations."), {"source": "NAV CANADA DAH", "topic": "Class F CYA/CYD/CYR details"}, {"source": "TC AIM", "topic": "Class F airspace"}],
    ),
    question(
        "b6-air-002",
        "airspace",
        "hard",
        "The planned launch point is outside controlled airspace, but wind drift or lost-link return could carry the RPA across the boundary. What should planning address?",
        "The pilot must account for the entire operating and contingency volume, including the possibility of inadvertent entry and required notification.",
        ["Only the launch point determines airspace requirements.", "Wind drift cannot create an airspace issue below 400 ft.", "Boundaries matter only to crewed aircraft."],
        "Airspace assessment should cover the planned and reasonably foreseeable contingency volume, not just where the aircraft takes off.",
        "Airspace boundary margin",
        "Plan lateral and contingency margins near controlled-airspace boundaries.",
        "CAR 901.15; TP 15263 Sections 1 and 6",
        [CARS, TP],
        [cars_ref("901.15", "Inadvertent entry into controlled airspace", "Notify if an uncontrolled RPA enters or is likely to enter controlled airspace."), tp_ref(1, "Air law, air traffic rules and procedures", "Controlled airspace", "Apply controlled-airspace rules to RPAS operations.")],
    ),
    question(
        "b6-air-003",
        "airspace",
        "medium",
        "A CYR restricted area is nearby but appears inactive on a planning app. What should the pilot do before relying on that display?",
        "Confirm the restriction details and current status using official aeronautical information such as the DAH and NOTAMs.",
        ["Trust the app because all apps are official sources.", "Ignore CYR areas if the aircraft remains below tree height.", "Use last year's printed screenshot."],
        "Unofficial planning tools can be helpful, but restrictions must be checked against authoritative current sources.",
        "Restricted airspace source validation",
        "Validate airspace status using authoritative publications rather than relying solely on third-party displays.",
        "TP 15263 Sections 1 and 6; DAH",
        [TP, DAH],
        [tp_ref(1, "Air law, air traffic rules and procedures", "Airspace restrictions", "Identify restricted airspace and required authorizations."), tp_ref(6, "Flight operations", "Pre-flight information", "Validate current aeronautical information before flight.")],
    ),
    question(
        "b6-nav-001",
        "navigation",
        "hard",
        "A coordinate is supplied in degrees and decimal minutes, but the flight app is set to decimal degrees. What is the main risk?",
        "Entering the coordinate without converting format can place the operation in the wrong location, possibly affecting airspace, aerodrome, or bystander risk.",
        ["Coordinate format changes only the label, not the location.", "The app will always infer the intended format.", "The error affects only map colour."],
        "Navigation errors can move the planned site significantly. Pilots must verify coordinate format and plotted location before flight.",
        "Coordinate format conversion",
        "Convert and verify coordinates using the correct format before operational use.",
        "TP 15263 Section 5",
        [TP],
        [tp_ref(5, "Navigation", "Latitude/longitude and coordinate formats", "Use coordinate formats correctly for flight planning.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-nav-002",
        "navigation",
        "medium",
        "A route is planned at a constant altitude above sea level across rising terrain. What must the pilot verify?",
        "That the RPA remains within required AGL limits and maintains obstacle/terrain clearance along the entire route.",
        ["ASL altitude automatically keeps AGL constant.", "Terrain matters only at launch.", "Rising terrain improves clearance."],
        "AGL changes as terrain elevation changes. RPAS pilots must reconcile ASL/AGL and obstacle clearance throughout the route.",
        "ASL versus AGL over terrain",
        "Relate ASL, AGL, terrain elevation, and operating limits during route planning.",
        "TP 15263 Section 5; CARs Part IX",
        [TP, CARS],
        [tp_ref(5, "Navigation", "Altitude references", "Calculate and interpret altitude references for flight planning."), cars_ref("901.27", "Maximum Altitude", "Comply with altitude limits unless an exception or authorization applies.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-nav-003",
        "navigation",
        "hard",
        "A pilot uses an old screenshot of a VNC to identify nearby obstacles and airspace. What is the best concern?",
        "The screenshot may be out of date, incomplete, or missing current aeronautical information, so current official sources must be checked.",
        ["Screenshots are valid indefinitely once saved.", "Only weather products expire.", "A VNC screenshot is better than current NOTAMs."],
        "Publication currency is part of navigation and pre-flight planning. Old static data can miss new obstacles, changed airspace, or temporary restrictions.",
        "Publication currency",
        "Verify currency and completeness of aeronautical publications used for navigation planning.",
        "TP 15263 Sections 5 and 6",
        [TP, AIM],
        [tp_ref(5, "Navigation", "Aeronautical publications and chart validity", "Determine validity of aeronautical publications."), tp_ref(6, "Flight operations", "Pre-flight information", "Use current information before flight.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-weather-001",
        "weather",
        "hard",
        "A TAF remains acceptable, but successive METARs show visibility and ceiling trending down faster than forecast. What should the pilot do?",
        "Treat the observed trend as a warning, reassess against operating minima and recovery options, and delay/cancel if margins are no longer adequate.",
        ["Use only the TAF because forecasts overrule observations.", "Continue if the first METAR was acceptable.", "Ignore ceiling trends for RPAS below 400 ft."],
        "Weather planning should compare forecasts with actual trends. Deteriorating observations may remove safe margins before the nominal forecast changes.",
        "Observed weather trend conflict",
        "Reconcile forecast and observed weather trends for conservative go/no-go decisions.",
        "TP 15263 Section 4; TC AIM MET",
        [TP, AIM],
        [tp_ref(4, "Meteorology", "Weather reports and forecasts", "Interpret weather information and trends for flight planning."), {"source": "TC AIM MET", "topic": "METAR/TAF interpretation and weather trends"}],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-reg-001",
        "regulations",
        "hard",
        "An Advanced pilot wants to fly closer to people using an RPA that is registered but not declared for the intended reduced-distance operation. What is the key regulatory problem?",
        "The pilot certificate alone is not enough; the aircraft must also meet the applicable declaration/technical requirements for the operation.",
        ["Registration alone gives all Advanced privileges.", "The rule applies only at night.", "A Basic certificate would allow closer operation."],
        "Advanced operations near people can depend on both pilot qualification and the RPAS meeting applicable technical/declaration requirements.",
        "Pilot privilege versus aircraft eligibility",
        "Distinguish pilot certification from RPAS declaration requirements for Advanced operations.",
        "CARs 901.69-901.70; TP 15263 Section 1",
        [CARS, TP],
        [cars_ref("901.69", "Manufacturer Declaration", "RPAS declaration for certain Advanced operations."), cars_ref("901.70", "Operation of a modified remotely piloted aircraft system", "Declared system must remain compliant when modified."), tp_ref(1, "Air law, air traffic rules and procedures", "Advanced operations requirements", "Apply certificate and aircraft requirements to Advanced operations.")],
    ),
    question(
        "b6-theory-006",
        "theory-of-flight",
        "medium",
        "A fixed-wing RPA is launched downwind from a short area because it is convenient for camera framing. What basic performance issue is being ignored?",
        "Downwind launch increases groundspeed needed over the surface and can reduce practical takeoff/climb margin in the available area.",
        ["Downwind launch always shortens takeoff distance.", "Wind direction affects only landing, not launch.", "Camera framing determines aircraft performance."],
        "Wind direction changes the relationship between airspeed and groundspeed. Launch/recovery direction affects practical performance margins.",
        "Wind direction and launch performance",
        "Apply wind and airspeed/groundspeed concepts to launch and recovery planning.",
        "TP 15263 Sections 4 and 7",
        [TP],
        [tp_ref(7, "Theory of flight", "Airspeed, groundspeed and performance", "Explain wind effects on aircraft performance."), tp_ref(4, "Meteorology", "Wind", "Assess wind direction and speed for operations.")],
        exam_scope="core-basic-advanced",
        exam_level="basic-advanced",
    ),
    question(
        "b6-vo-005",
        "visual-observers",
        "medium",
        "An observer is positioned where they can hear the pilot but must look into low sun for most of the operation. What should be changed?",
        "Reposition, shade, rotate, or reschedule so the observer can effectively scan the operating airspace.",
        ["Keep the position because voice contact is enough.", "Tell the observer to scan only the ground.", "Use sunglasses as the only possible mitigation regardless of effectiveness."],
        "Observer placement must support actual visual detection. Low sun can reduce detection performance and should be mitigated in planning.",
        "Observer placement and sun angle",
        "Select observer positions that support effective visual scanning.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Vision and scanning limitations", "Explain visual limitations affecting detection."), tp_ref(6, "Flight operations", "Visual observer duties", "Place observers to support traffic and hazard detection.")],
    ),
    question(
        "b6-notam-005",
        "notams",
        "medium",
        "A NOTAM is cancelled shortly before launch, but another NOTAM for the same area remains active with different times. What should the pilot do?",
        "Review the complete current NOTAM set and base the decision on all active notices, not the cancellation of one notice.",
        ["Assume all hazards are cancelled.", "Use the cancelled NOTAM because it was printed first.", "Proceed without checking the remaining active notice."],
        "A cancellation affects only that notice. The pilot must review the complete current briefing to avoid missing overlapping or replacement NOTAMs.",
        "NOTAM cancellation and replacement",
        "Review current NOTAMs as a set and identify active notices affecting the operation.",
        "TP 15263 Section 6; TC AIM",
        [TP, AIM],
        [tp_ref(6, "Flight operations", "Pre-flight information", "Use current aeronautical information before flight."), {"source": "TC AIM", "topic": "NOTAM status and validity"}],
    ),
    question(
        "b6-abn-005",
        "abnormal",
        "hard",
        "A return-to-home function starts climbing toward a height that would enter an overlying controlled-airspace shelf. What should the pilot have verified before flight?",
        "The programmed emergency altitude and route were compatible with airspace, obstacles, and the authorized operating volume.",
        ["Only the normal mission altitude matters.", "Return-to-home altitude is always legal if factory-set.", "Controlled airspace cannot be affected by automated emergency functions."],
        "Emergency automation can leave the planned operating envelope if not configured. Pre-flight checks should include programmed contingency behaviour.",
        "Emergency automation configuration",
        "Verify automated emergency settings against airspace and obstacle constraints.",
        "TP 15263 Sections 2 and 6; CARs Part IX",
        [TP, CARS],
        [tp_ref(2, "RPA systems", "Automated functions and settings", "Understand automated system behaviours."), tp_ref(6, "Flight operations", "Emergency procedures", "Configure and brief emergency procedures before flight.")],
    ),
    question(
        "b6-safety-005",
        "safety",
        "hard",
        "A cordon keeps bystanders out of the launch area, but no one monitors a side entrance. What is the weakness in the control?",
        "An unmonitored access point can defeat the cordon, so site control needs active monitoring or a physical/control redesign.",
        ["A cordon works once announced.", "Side entrances are irrelevant if the pilot is focused.", "Bystander controls apply only during takeoff."],
        "Risk controls must be effective in practice. A cordon without monitoring can fail when bystanders enter unexpectedly.",
        "Cordon effectiveness",
        "Evaluate whether public-safety controls are actively maintained during the operation.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Risk controls and monitoring", "Assess whether mitigations remain effective."), tp_ref(6, "Flight operations", "Site control", "Maintain control of the operating area.")],
    ),
    question(
        "b6-air-004",
        "airspace",
        "medium",
        "A planned operation is below 400 ft AGL but inside Class C control zone boundaries. What is the key requirement?",
        "The pilot must have the required airspace authorization/instructions for that specific controlled-airspace operation.",
        ["The 400 ft limit alone permits the flight.", "Class C boundaries apply only above circuit altitude.", "Authorization is optional if the RPA weighs under 25 kg."],
        "Altitude below 400 ft does not remove controlled-airspace requirements. Advanced operations in controlled airspace require authorization and compliance.",
        "Controlled airspace below 400 ft",
        "Apply controlled-airspace authorization requirements to RPAS operations below 400 ft.",
        "CAR 901.71; CAR 901.72; TP 15263 Section 1",
        [CARS, TP],
        [cars_ref("901.71", "Operations in Controlled Airspace", "Authorization required for controlled-airspace RPAS operation."), cars_ref("901.72", "Compliance with air traffic control instructions", "Comply with ATC instructions.")],
    ),
    question(
        "b6-maint-005",
        "maintenance",
        "medium",
        "A maintenance log shows repeated motor-temperature warnings on previous flights, but no current warning appears during setup. What should the pilot do?",
        "Investigate the recurring trend before flight because repeated warnings can indicate an unresolved serviceability issue.",
        ["Ignore old warnings if today's app screen is clear.", "Delete the log to avoid confusion.", "Fly until the warning becomes permanent."],
        "Maintenance and records help identify trends. Recurring warnings can indicate a defect even if the current pre-flight status looks normal.",
        "Recurring defect trends",
        "Use records and prior warnings to assess continuing serviceability.",
        "TP 15263 Section 2; CARs Part IX",
        [TP, CARS],
        [tp_ref(2, "RPA systems", "Maintenance and defects", "Identify recurring defects and serviceability concerns."), cars_ref("901.48", "Records", "Maintain records relevant to the RPAS and operations.")],
    ),
    question(
        "b6-sys-005",
        "aircraft-systems",
        "medium",
        "A pilot changes camera payloads and the aircraft now takes longer to stop from forward flight. What system/performance issue should be considered?",
        "Changed mass and drag can alter braking distance, control response, and obstacle-clearance margins.",
        ["Payloads affect only image quality.", "Forward stopping distance is fixed by regulation.", "Drag decreases whenever payload weight increases."],
        "Payload changes can affect inertia, drag, balance, and control response. Obstacle and buffer margins should reflect the configured aircraft.",
        "Payload effects on response",
        "Assess how payload changes affect response, stopping distance, and flight margins.",
        "TP 15263 Sections 2 and 7",
        [TP],
        [tp_ref(2, "RPA systems", "Payload configuration", "Identify payload effects on aircraft operation."), tp_ref(7, "Theory of flight", "Performance and control response", "Explain performance effects caused by configuration changes.")],
    ),
    question(
        "b6-fp-004",
        "flight-planning",
        "medium",
        "A flight plan relies on one observer, one radio monitor, and one payload operator, but all roles are assigned to the pilot. What is the planning problem?",
        "The workload is unrealistic; critical monitoring and decision tasks should be assigned so the pilot can maintain safe control.",
        ["More roles assigned to the pilot always improves accountability.", "Payload work is the same as airspace monitoring.", "Crew role planning is optional in Advanced operations."],
        "Human factors and flight planning require realistic workload management. Overloading the pilot can reduce control and situational awareness.",
        "Crew role workload planning",
        "Allocate crew duties to preserve pilot control and situational awareness.",
        "TP 15263 Sections 3 and 6",
        [TP],
        [tp_ref(3, "Human factors", "Workload management", "Recognize and manage workload."), tp_ref(6, "Flight operations", "Crew roles and responsibilities", "Plan roles for safe operation.")],
    ),
]


def main():
    pool = {
        "batch": "Batch 6",
        "description": "Additional Advanced RPAS quiz questions generated 2026-10-01 with weak-topic emphasis.",
        "categoryTargets": CATEGORY_TARGETS,
        "questions": SPECS,
    }
    out = Path(__file__).with_name("Batch6_candidate_pool.json")
    out.write_text(json.dumps(pool, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {len(SPECS)} candidates to {out}")
    print(f"Target selected count: {sum(CATEGORY_TARGETS.values())}")


if __name__ == "__main__":
    main()
